name: "Check"

on:
  pull_request:
  push:

jobs:
  check-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install Nix
      uses: cachix/install-nix-action@v13
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210604_8e6ee1b/install
        extra_nix_config: |
          experimental-features = nix-command flakes
    - name: Setup Cachix
      uses: cachix/cachix-action@v10
      with:
        name: linyinfeng
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        extraPullNames: nix-community
    - name: Check
      run: nix flake check --verbose --print-build-logs
